### ISSUE TITLE
Making use of exception classes

### ISSUE THREAD

**Issue by sladkovm** [hozn/stravalib#107]
Hi, 

how do I make use of the exception classes? Should I assume that, if limit is exceeded, all *ConnectionError* and *ConnectionResetError* will be caught by the lib and the *stravalib.exc.RateLimitExceeded* will be raised?

I'm trying to `except(stravalib.exc.RateLimitExceeded)` to trigger waiting time, but it does not help.

**Comment by hozn** [comment]
You can see the implementation of the default rate limiter here:  https://github.com/hozn/stravalib/blob/master/stravalib/util/limiter.py

In general, the use of a limiter is designed to avoid ever having the rate limit exceeded (it will attempt to sleep, etc.).  You may wish to make your own rate limiter implementation too and use that in your client.  (Hopefully comments for classes above are clear enough to support that.)

If the rate limited is created with `raise_exc=True` flag, then it will raise the RateLimitExceeded exception instead of attempting to sleep, etc. to avoid such an exception.

In that case, you should be able to catch it as you describe:

```python
try:
  client.some_method()
except RateLimitExceeded as x:
  logger.exception("Rate limit was exceeded.")
```

Currently the client is not inspecting the error messages coming back from Strava; I believe that there are headers that would indicate whether the rejection is due to a rate limit issue, though I've not looked into this.  We'd certainly welcome any pull request that could transform those into exception subclasses that indicates that the cause of the failure is a rate-exceeded.

**Comment by sladkovm** [comment]
Ok, thanks. If I understand correctly the default limiter is enabled by default. I will inspect in more details what sort of ConnectionError I receive from the remote host.
