### ISSUE TITLE
Cannot set value of `kom_type` in `SegmentLeaderboard`

### ISSUE THREAD

**Issue by tijmenjoppe** [hozn/stravalib#138]
When retrieving the leaderboard for a segment, the `kom_type` value in the `SegmentLeaderboard` class cannot be set.

(Quick fix I did was replace the `ChoicesAttribute` of `kom_type` by a simple `Attribute(six.text_type)`).

**Comment by hozn** [comment]
Thanks for letting me know. I must have made a mistake with that "enum". I'll fix this for 0.8.1

**Comment by hozn** [comment]
Incidentally, @tijmenjoppe , can you tell me what the value of `kom_type` was that it was refusing to set?  (I tested this with a canned/saved raw json for an activity, which worked as expected.)  I will set this to a regular string attr, though, either way, since I don't really trust Strava's docs to comprehensively describe the valid values.

**Comment by hozn** [comment]
Ok, fixed in 0.9.0
