### ISSUE TITLE
client.expore_segments gives no such attribute error

### ISSUE THREAD

**Issue by greenpasta** [hozn/stravalib#50]
No such attribute starred on entity \<SegmentExplorerResult id=123456 name='Segment Name' resource_state=2>

**Comment by greenpasta** [comment]
And client.get_segment_leaderboard giving these:

Unable to set attribute neighborhood_index on entity \<SegmentLeaderboardEntry rank=None athlete_name=None>
No such attribute kom_type on entity \<SegmentLeaderboard >
No such attribute neighborhood_count on entity \<SegmentLeaderboard >

**Comment by felixhfly** [comment]
Greenpasta,
Did you get a resolution to this? I have a similar issue with many calls including
  client.get_segment(segment_id = 6695759)
which results:
  No such attribute athlete_segment_stats on entity <Segment id=None name=None resource_state=None>
This makes calls very noisy especially if the call gets a lot of different results. Otherwise the calls do seem to be recovering the required information. 

I have tried catching warnings using the warnings module, but not got it working.  The next step seems to be assessing the stravalib code, so any ideas would be very welcome.

**Comment by hozn** [comment]
Sorry, this fell off my radar;  the fix should be a pretty quick one so I will try to get it wrapped up shortly (unless anyone beats me to it with a PR).

**Comment by felixhfly** [comment]
Thanks Honz. If you want to let me have an early version or anything I'm happy to test.  I'm currently working with get_segement and get_segement_efforts methods and both give similar results.

**Comment by hozn** [comment]
get_segment specifically has been fixed, but I will continue to look into the others. I'm trying to rework the functional test framework a bit -- or at least provide scripts to make it easier for people to get tokens and test.  Unfortunately many of our tests are only accessible to the authorized user, so I think we'll be distributing tokens for the Stravalib Tester user to developers so they can use that to write functional tests.  It's tricky, since the underlying data (leaderboards, etc.) are constantly changing, even if we can restrict activities, etc.  Anyway ... work continues here.

**Comment by hozn** [comment]
Mistagged the commit, sadly.  It was ad7a578.

**Comment by felixhfly** [comment]
I have tried pulling this commit, but have not got it to work at all.  (I'm using Python 3 via 2to3 which may make a difference.)
This issue is client.get_segment(segment_id = xxx) now gives a ValueError on a date time format.

If anyone else has the original logging issue, my workaround has been to revert to the PIP install version 0.5, and change     
   self.log.warn("No such attribute {0} on entity {1}".format(k, self))
to
    self.log.info("No such attribute {0} on entity {1}".format(k, self))
in model.py.

**Comment by hozn** [comment]
Thanks for the feedback; I'm sorry this isn't working.  It is true I have
been using python2, so I will test this change in python3.

**Comment by paulsavala** [comment]
Just wanted to add to this that I'm getting neighborhood_index problems when trying to grab segment leaderboard entries. I'm using version 0.5.1 (and had the same issue with 0.5.0).

**Comment by hozn** [comment]
Thanks. I will check on this. I haven't used this part of the Ali recently.
